version: '3.9'

services:
  db:
    image: postgres
    #container_name: postgres_container
    environment:
      #POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: 1234
      #POSTGRES_DB: yourdatabase
    #ports:
      #- "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: